	<?php Template::setTitle('Tips For Writing Effective Titles'); ?>
Writing a good title for your listing is important because it will help Work It, Mom! members and people who are not on Work It, Mom! find it through search engines.
  <ul>
    <li><strong>Your Title will become the title tag for your listing. </strong>Title tags are important because they help people outside of Work It, Mom! to find your listing when they search for something using a search engine, like Google or Yahoo. Title tags appear in the top left corner of the page -- look up and you'll see the title tag for this page you're on -- and they are by far, the most important tools to help your listing appear in search results outside of Work It, Mom!</li>
    <li><strong> Start your description with keywords that are appropriate for your product or service instead of the proper name of your product or service</strong> (E.g. Custom greeting cards - Susan's Card Design Store instead of  Susan's Card Design Store - Custom Greeting Cards) This will help search engines pick it up when someone outside of Work It, Mom! searches for one of the keywords you've included. It will also help your listing come up when someone searches for it in our Marketplace.</li>
    <li><strong> Remember, search engines only read the first 4-5 words in your description, so start your description with your most important keywords for which you want your listing to be optimized</strong>. Try not to use words like "a", "the", "to", "great" in the first 4-5 words since they just take up space and don't do anything for search engines. (E.g. Great Greeting Cards For Your Kids is not a great description because "great", "for", "your" are generic words that don't optimize your listing for what you're really targeting. A better way would be to say Kids Greeting Cards.)</li>
    <li><strong> We want your title to be easy to read for search engines</strong> and people who are looking for something on Work It, Mom! or in the marketplace, so make sure it's not too long and is easy to understand.</li>
  </ul>
 If you'd like more information on how to write a good Titles (which will become your title tags), check out this <a target="_blank" href="http://www.sprydev.com/title-tags-search-engines-and-your-customers-will-">great article</a> by Ben Finklea, the CEO of <a target="_blank" href="http://www.sprydev.com/">Sprydev</a>, a leading Search Optimization Firm that works with small businesses.
