	<?php Template::setTitle('Terms and Conditions'); ?>

	<div style="height:300px; overflow:auto;">
		<p>PLEASE READ THE FOLLOWING TERMS OF SERVICE RELATING TO YOUR USE OF THE WORK IT, MOM! WEBSITE CAREFULLY. THESE TERMS OF SERVICE GOVERN YOUR USE OF THE WORK IT, MOM! WEBSITE AND ALL SERVICES OFFERED THROUGH THE WEBSITE.</p>
		<p>These Terms of Service (“TOS”) apply to all users of the Work it, Mom!™ website (the “Site”). By using this Site (including any content posted on the Site), you signify your acceptance of these TOS, as well as the Work it, Mom! Privacy Policy, which is incorporated by reference into these TOS. Work it, Mom! reserves the right to update or change these TOS at any time by posting the most current version of the TOS on the Site. Your continued use of the Site after we post any changes to the TOS signifies your agreement to any such changes. If you do not agree to these TOS, you must discontinue using the Site and terminate your membership in Work it, Mom!. This Site is owned and operated by Work it, Mom! LLC.</p>
		<p>Website Access.<br />
			THIS SITE AND THE SERVICES OFFERED ARE INTENDED ONLY FOR INDIVIDUALS 16 YEARS OLD OR OLDER. BY ACCESSING THIS SITE, YOU ARE CERTIFYING THAT YOU ARE AT LEAST 16 YEARS OF AGE. USE OF THE SITE AND THE SERVICES IS VOID WHERE PROHIBITED.</p>
		<p>Registering as a Member.<br />
			You do not have to be a Work it, Mom! Member to use this Site. However, only Members can use some of the most popular features and services that Work it, Mom! currently offers, such as message boards, articles, member profiles, and social networking features, or other services that we may offer in the future (the “Services”). Registration is free.</p>
		<p>When you register with Work it, Mom!, you will be asked to provide us with your name, email address, and other information that we may request, all of which will become part of your profile (“Profile Data”), and which you can add to or change from time to time. You will also be asked to select a screen name and password which will serve to identify you as a Member each time you visit the Site and allow you to access your account. You may not (i) select or use a screen name of another person with intent to impersonate that person, (ii) use a screen name in which another person has rights without authorization from that person, or (iii) use a screen name that Work it, Mom!, at its sole discretion, deems offensive You agree to provide (i) true, accurate, current and complete information about yourself as prompted by the registration form, and (ii) maintain and properly update the Profile Data to keep it true, accurate, current and complete. If you provide information that is untrue, inaccurate, not current or incomplete, or Work it, Mom! has reasonable grounds to suspect that you have, we have the right to suspend or terminate your membership and refuse any and all current or future use of the Site and the Services (or any portion thereof). Members must immediately notify Work it, Mom! of any known or suspected unauthorized use of a Member's account, or any known or suspected breach of security, including loss, theft, or unauthorized disclosure of Member's password. Members should be cautious about sharing their account information with third parties. Each Member is responsible for the confidentiality of her/his screen name and password and all usage or activity on her/his account, including use of the account by any third party, whether or not such use is authorized by the Member. Members may share an account (using one screen name and password) if the account is being used for legitimate group discussions and if it is clearly disclosed that it is a group account.</p>
		<p>How You Can Use the Services.<br />
			This Site and the Services offered are intended for your personal, noncommercial use in accordance with these TOS. You agree that you will not (i) copy, display or distribute any part of the Site, in any medium, without Work it, Mom!’s prior written consent, or (ii) alter or modify any part of the Site other than as may be reasonably necessary to use the Site for its intended purpose.</p>
		<p>You further agree that you will not use any automated devices, such as spiders, robots or data mining techniques to catalog, download, store or otherwise reproduce, store or distribute content available on the Site, or to manipulate the Site or the Services, or otherwise exceed the limited access granted to you by Work it, Mom!. You will take no action to interfere with, interrupt, destroy or limit the functionality of the Site or any computer software or hardware or telecommunications equipment. You will not distribute or transmit any content or software or other computer files that contain a computer virus or other harmful component.</p>
		<p>Controlling your Personal Information<br />
			One of the great features of Work it, Mom! is that you control who will see your profile information as well as any other information or photos that you post on the Site, simply by adjusting your Privacy Settings. When you first create a profile, or when you make any changes to it, you can select who will see that information. In almost cases (there are a few exceptions, described below), you can make your profile information completely private, so that no one sees it but you. You can also choose to make your profile information (or parts of it) visible only to the friends in your network. Or you can choose to make it visible to everyone who visits the Site.</p>
		<p>You also have control over the personal information you post to the Site through photos and other features. Each time that you make a post to the Site, you’ll be prompted to choose who you want to see that post. You can choose to share photos and posts with your network of friends, or you can choose to share them with everyone. You can change your privacy selection for a particular post at any time by editing the original post/photo and changing the privacy setting in the “Privacy” area of the edit page. However, that change will only affect that particular piece of content. Be aware that if you choose to make your posts visible to everyone, then any personal information you post will be accessible to all Members and all visitors to the Site. You should also be aware that any information that is made public on the Site will be searchable by other search engines. In addition, even if that content is later removed from this Site, it may still be stored in other computers of people who visited the Site, and removal of that information from this Site will not remove it from those other computers. Therefore, we caution you to be very careful about posting personal information to the Site.</p>
		<p>In addition, some information that you add to your profile cannot be hidden and is always visible to anyone who visits that Site. That includes your avatar, your screen name and your location. In addition, you will show up in searches on the Site based on your ZIP/Postal code. If you’re uncomfortable disclosing this information, just make something up. The point is, be aware that the information you post will be viewed by many people who you don’t know and you should exercise good judgment and discretion when you choose to post personal information.</p>
		<p>Work it, Mom! makes every effort to ensure that your Profile Data and posts are displayed only to the people you selected in your privacy settings. However, mistakes can happen. If you believe that your content is being displayed in a manner that you did not authorize, you can notify us of the error by using the Feedback button on any page of the Site and we will correct the problem promptly. However, you agree that your sole remedy against us if we were to make such a mistake is to require us to change the privacy settings to those that you originally requested.</p>
		<p>User Guidelines<br />
			As an online community, we will thrive only if we can rely on our Members to act responsibly. We believe that all Members and visitors benefit from basic rules regarding conduct while using the Site and the Services. Accordingly, we have developed Guidelines which we hope will increase your awareness of your responsibilities to others when using the Site and the Services and will enhance your enjoyment of the Site. We may update these Guidelines from time to time.</p>
		<p>The following Guidelines apply to and govern your use of the Site and the Services.</p>
		<p> * Treat other Members in the community with respect. Even if their views differ from yours, they have the right to be heard.<br />
			* Do not post email addresses, telephone numbers, street addresses, last names, or any other content or information that identifies a user.<br />
			* Do not upload, post, email, transmit or otherwise make available content that is unlawful, abusive, hateful, vulgar, obscene, pornographic, libelous, defamatory, harassing, or invasive of another person’s privacy, or is racially or ethnically offensive or which personally attacks someone because of their opinions, values, beliefs or choices. Any harassing messages or postings that might be construed as threatening or stalking will be deleted and made available to the proper law enforcement officials, at our discretion. We also reserve the right to remove postings that are off the subject or not in English. In all cases, we are the final judge on whether these Guidelines have been violated.<br />
			* You may not encourage, engage in or promote any unlawful conduct while on our Site. If you do so, your membership will be terminated.<br />
			* Advertising is prohibited except in areas of the Site which are expressly designated for advertising. Do not use any of the other areas of the Site for advertising. This includes the promotion of your home or personal business or solicitation of clients for your personal or home business.<br />
			* We don’t allow spamming. Sending the same message multiple times or to multiple people will be treated as spam. Repeat “spammers” will be banned from the Site.<br />
			* Do not impersonate any person or entity or misrepresent your identity or affiliation with any person or entity.<br />
			* If a Member requests that you no longer communicate with her, please honor that request.</p>
		<p>If you believe that any postings, photos or other content on the Site violates these Guidelines or these TOS, please let us know by using the Report Abuse on every page of the Site. However, in all cases, we are the final judge on whether these Guidelines or the TOS have been violated and we will determine what, if any, action should be to taken.</p>
		<p>Our Content Removal Rights.<br />
			We reserve the right, but not the obligation, to monitor, edit or remove any content at any time and without notice if we believe that (i) the content violates these TOS, (ii) removal is necessary to protect the rights, property or personal safety of Work it, Mom!, its users and the public, or (iii) if required to do so by law. We can also remove content if we believe that doing so will improve our Site and the experience of our Members.</p>
		<p>You acknowledge that by using the Site, you may be exposed to content that you find objectionable, indecent or offensive or which is inaccurate, misleading or incomplete. We are not responsible for the accuracy, completeness or usefulness of any content, nor do we endorse such content. We do not verify the identity of people using our Site, and you assume the risk of believing any content you read.</p>
		<p>Notwithstanding anything to the contrary stated herein or in our Privacy Policy, we have the right to view and monitor any content posted to this Site, even if that content has been designated as “private,” if we have reason to believe that the content or the Member posting the content has violated these TOS or the incorporated Guidelines, or has engaged in conduct that is fraudulent, deceitful, unlawful or is or could be a threat to persons or property.</p>
		<p>Rights to Use Content<br />
			You take responsibility for all content that you upload, post or distribute on the Site and the consequences of publishing and posting that content. In connection therewith, you represent and warrant that (i) you own or have the necessary rights and licenses to upload, post and distribute that content and to authorize Work it, Mom! and its Members to use that content in the manner contemplated by these TOS, (ii) you have the written consent of every person identified in that content to use their name, likeness and/or photograph in connection with the use of the content as contemplated by these TOS. You agree that you will not upload, post, email or otherwise transmit any content that infringes and/or violates the right of a third party or any law, rule or regulation including but not limited to (i) copyright, patent, trademark, trade secret, or other proprietary right, (ii) right of privacy or publicity; (iii) any confidentiality obligation; or (iv) any content which you do not have a right to upload.</p>
		<p>By submitting content to the Site, you grant to Work it, Mom! and its successors in business a perpetual, worldwide, royalty-free, and non-exclusive license to reproduce, distribute, modify, edit, display, adapt, create derivative works from and market and promote the content, for any commercial purposes, and in any medium now existing or hereinafter developed, and to use your name, likeness and any personal information you submit with the content without your prior approval or the payment of any compensation. You also grant each user of the Work it, Mom! Site a non-exclusive license to access your content as permitted through the functionality of the Site and under these TOS.</p>
		<p>Proprietary Rights<br />
			The Site and all material published on the Site, including, but not limited to text, photographs, video, text, graphics, music, sounds, messages, comments, ratings, and other materials is owned by Work it, Mom! or its licensors and is protected by copyright, patents, trademarks, trade secrets and/or other proprietary rights, including under the United States copyright laws. Work it, Mom! owns a copyright in the selection, coordination, arrangement and enhancement of such content and a copyright in the Site.</p>
		<p>All trademarks appearing on this Site (&quot;Marks&quot;) are trademarks of their respective owners, including Work it, Mom! and its partners. Users are prohibited from using any Marks without the written permission of Work it, Mom! or such third party that may own the Marks.</p>
		<p>Content on the Site is provided AS IS for your information and personal use only. You may not copy, publish, transmit, distribute, perform, sell, create derivative works of, or in any way exploit, any of the content, in whole or in part, without Work it, Mom!’s prior written consent. You may download content for your personal, non-commercial use only as provided in these TOS, provided that you keep intact all copyright and other proprietary notices. Copying or storing of content for other than personal use is expressly prohibited without prior permission from us or the copyright holder identified in the copyright notice contained in the content.</p>
		<p>No License Granted.<br />
			Except for allowing you to use the Site for your personal use as set forth in the paragraph above, when you use the Site, you are not receiving a license or any other rights from us, including intellectual property or other proprietary rights of Work it, Mom!. YOU UNDERSTAND THAT YOU HAVE NO RIGHTS TO THE SERVICES OR ANY OTHER WORK IT, MOM! PROPERTY EXCEPT AS WE INDICATE IN THESE TERMS.</p>
		<p>Protecting Children.<br />
			Because the safety of children is very important to us, Work it, Mom! complies with the Children's Online Privacy Protection Act. Work it, Mom! does not encourage participation or visitation by children. Visitors who are known to be under the age of 16 are prohibited from becoming Work it, Mom! Members. Work it, Mom! does not knowingly collect personal information from children under the age of 16.</p>
		<p>Communications from Work it, Mom!.<br />
			By registering for Work it, Mom!, you will receive online communications from Work it, Mom!. To unsubscribe from any Work it, Mom! email list, simply click on the “Unsubscribe” link at the bottom of the email and your name will be removed from that mailing list.</p>
		<p>Links.<br />
			The Site, or Members, may provide links to other World Wide Web sites or resources. Because Work it, Mom! has no control over such sites and resources, you acknowledge and agree that Work it, Mom! is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials or available from such sites or resources. You further acknowledge and agree that Work it, Mom! shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>
		<p>Indemnity.<br />
			You understand that you are personally responsible for your behavior while on the Site and agree to indemnify and hold Work it, Mom!, and its affiliates, business partners, and their respective officers, directors, employees, and agents, harmless from and against any loss, damage, liability, cost, or expense of any kind (including attorneys' fees) that we may incur in connection with a third party claim or otherwise, in relation to your use of the Services or access to the Site, or your violation of either these TOS, applicable law or the rights of any third party.</p>
		<p>Disclaimer of Warranties.<br />
			YOU UNDERSTAND THAT YOUR USE OF THE SITE AND SERVICES (INCLUDING ANY DOWNLOADS OR ANY LOSS OF DATA OR OTHER DAMAGE TO YOUR COMPUTER SYSTEM YOU EXPERIENCE FROM USING THE SITE AND SERVICES) IS AT YOUR SOLE RISK. YOU UNDERSTAND THAT THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS AND OTHER CONTENT (INCLUDING THIRD PARTY INFORMATION, PRODUCTS AND CONTENT INCLUDED IN OR ACCESSIBLE FROM THE SITE OR SERVICES, ARE PROVIDED ON AN &quot;AS IS&quot; &quot;WHERE-IS&quot; AND &quot;WHERE AVAILABLE&quot; BASIS, AND ARE SUBJECT TO CHANGE AT ANY TIME WITHOUT NOTICE TO YOU. YOU ACKNOWLEDGE THAT WORK IT, MOM! MAKES NO WARRANTY THAT THE SITE OR SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE. YOU UNDERSTAND THAT WORK IT, MOM! DOES NOT WARRANT THAT THE RESULTS OBTAINED FROM YOUR USE OF THE SITE OR SERVICES WILL MEET YOUR EXPECTATIONS. NO WARRANTY OF ANY KIND, WHETHER ORAL OR WRITTEN, CAN MODIFY THE TERMS OF THE DISCLAIMER SET FORTH IN THIS DOCUMENT.</p>
		<p>YOUR USE AND BROWSING OF THE SITE IS AT YOUR OWN RISK. IF YOU ARE DISSATISFIED WITH ANY OF THE MATERIALS CONTAINED IN THE SITE OR SERVICES, OR WITH ANY OF THESE TOS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING AND USING THE SITE AND SERVICES.</p>
		<p>TO THE FULLEST EXTENT PERMITTED BY LAW, WORK IT, MOM! DISCLAIMS ALL REPRESENTATIONS, WARRANTIES, AND CONDITIONS OF ANY KIND (EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS) AS TO THE SITE AND SERVICES AND ALL INFORMATION, PRODUCTS, AND OTHER CONTENT (INCLUDING THIRD PARTY INFORMATION, PRODUCTS, AND CONTENT) INCLUDED IN OR ACCESSIBLE FROM THE SITE AND SERVICES.</p>
		<p>THE INFORMATION IS PROVIDED WITH THE UNDERSTANDING THAT WORK IT, MOM! IS NOT ENGAGED IN RENDERING LEGAL, MEDICAL, FINANCIAL, COUNSELING, OR OTHER PROFESSIONAL SERVICES OR ADVICE. WORK IT, MOM! ENCOURAGES YOU TO SEEK APPROPRIATE PROFESSIONAL ADVICE OR CARE REGARDING ANY SITUATION THAT REQUIRES SUCH ATTENTION.</p>
		<p>Liability Disclaimer.<br />
			TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL WORK IT, MOM! OR ITS AFFILIATES BE LIABLE TO YOU (OR ANY THIRD PARTY MAKING CLAIMS THROUGH YOU) FOR ANY DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO ANY DIRECT, INDIRECT, SPECIAL, CONSEQUENTIAL, PUNITIVE OR INCIDENTAL DAMAGES, OR DAMAGES FOR LOSS OF USE, PROFITS, DATA, OR OTHER INTANGIBLES, OR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, UNAUTHORIZED ACCESS TO AND TAMPERING WITH YOUR PERSONAL INFORMATION OR TRANSMISSIONS, ARISING OUT OF OR RELATED TO THE USE, INABILITY TO USE, UNAUTHORIZED USE, PERFORMANCE, OR NON-PERFORMANCE OF THE SITE OR THE SERVICES, EVEN IF WORK IT, MOM! HAS BEEN ADVISED PREVIOUSLY OF THE POSSIBILITY OF SUCH DAMAGES AND WHETHER SUCH DAMAGES ARISE IN CONTRACT, NEGLIGENCE, TORT, UNDER STATUTE, IN EQUITY, AT LAW, OR OTHERWISE.</p>
		<p>If any part of these warranty disclaimers or limitations of liability is found to be invalid or unenforceable for any reason, then our aggregate liability for all claims under such circumstances for liabilities, shall not exceed ten dollars ($10).</p>
		<p>Access Restrictions; Termination.<br />
			We can suspend or terminate your membership in Work it, Mom! and your access to the Site or the Services, in whole or in part, at any time, immediately and without notice if, at Work it, Mom!’s sole discretion, you fail to comply with any of the TOS or the Guidelines. Upon termination, you must destroy all materials obtained from this Site and the Services and all copies thereof. In the event of suspension or termination, you are no longer authorized to access the Site or the Services, and the restrictions imposed on you with respect to any materials downloaded from the Site or the Services and the disclaimers and limitations of liabilities set forth in the TOS shall survive.</p>
		<p>You understand and agree that your membership in Work it, Mom! is subject to and conditioned upon the following: Your continued adherence to these TOS and any future modifications thereto. Your violation of these TOS or any other agreement between you and Work it, Mom! constitute grounds for immediate termination of your membership without further notice at Work it, Mom!’s sole discretion. We may also terminate your membership at any time, immediately and without notice, if we determine, in our sole discretion, that your conduct is detrimental to our business or the Work it, Mom! community. Termination of your membership will result in cancellation of all rights of access and use granted to Members. Work it, Mom! reserves the right to change, discontinue or suspend Work it, Mom! or any of the Services at any time for any reason. Members may terminate their membership at any time by sending their request to us, using the “Send Feedback” button on any page of the Site. Work it, Mom! shall be the sole determiner in cases of suspected abuse, fraud, or breach of these TOS. Any decision Work it, Mom! makes relating to termination or suspension of any Member's account shall be final and binding. Work it, Mom! may terminate any Member's account at its sole discretion if a Member has been inactive for a period of twelve (12) months. A Member will be defined as inactive if she has not logged into the Site with her screen name and password, or contacted Work it, Mom! in any other manner. In addition, if you have been inactive for three (3) months, we may take down any photos that you have posted to your profile or anywhere else on the Site.</p>
		<p>Digital Millennium Copyright Act (&quot;DMCA&quot;) Notice<br />
			Materials may be made available via the Site and the Services by third parties not within our control. We are under no obligation to, and do not, scan content posted, however, we respect the copyright interests of others. It is our policy not to permit materials known by us to infringe another party's copyright to remain on the Site or the Service.</p>
		<p>If you believe any materials on the Site or the Service infringe a copyright, you should provide us with written notice that at a minimum contains:</p>
		<p>(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
		<p>(ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
		<p>(iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to<br />
			permit us to locate the material;</p>
		<p>(iv) Information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</p>
		<p>(v) A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
		<p>(vi) A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
		<p>All DMCA notices should be sent to us via email at: info at workitmom.com</p>
		<p>Third Party Products and Services<br />
			You may order services, merchandise or other products through our Site from other parties (collectively, the &quot;Third Party Sellers&quot;). All matters concerning the services, merchandise and other products desired from the Third Party Sellers including, but not limited to, purchase terms, payment terms, warranties, guarantees, maintenance and delivery, are solely between you and the Third Party Sellers. We make no warranties or representations whatsoever with regard to any services, merchandise or other products provided by the Third Party Sellers. You will not consider us (and we will not be construed as) a party to such transaction, whether or not we may have received some form of revenue or other remuneration in connection with such transactions, and we will not be liable for any costs or damages arising out of, either directly or indirectly, you or any other person involved or related to the transactions.</p>
		<p>Miscellaneous.<br />
			These TOS are the entire agreement between you and Work it, Mom!. They supersede any and all prior or contemporaneous agreements between you and Work it, Mom! relating to your use of the Site or the Services. If any part of these TOS is determined to be invalid or unenforceable, it will not impact any other provision of these TOS, all of which will remain in full force and effect. The failure of Work it, Mom! to partially or fully exercise any rights or the waiver of Work it, Mom! of any breach of these TOS by you, shall not prevent a subsequent exercise of such right by Work it, Mom! or be deemed a waiver by Work it, Mom! of any subsequent breach by you of the same or any other term of these TOS. The rights and remedies of Work it, Mom! under these TOS and any other applicable agreement between you and Work it, Mom! shall be cumulative, and the exercise of any such right or remedy shall not limit Work it, Mom!'s right to exercise any other right or remedy.</p>
		<p>These TOS are governed by, and will be interpreted in accordance with, the laws of the State of Massachusetts, without regard to any choice of law provisions. You agree that, with the exception of injunctive relief sought by Work it, Mom! for any violation of Work it, Mom!’s proprietary or other rights, any and all disputes relating to these TOS, your use of the Site or the Services shall be resolved by arbitration in accordance with the then-current rules of the American Arbitration Association (the &quot;AAA&quot;) before an independent arbitrator designated by the AAA. The location of arbitration shall be Boston, MA, USA.</p>
		<p>The workitmom.com website is owned and operated by Work it, Mom! LLC.</p>
	</div>

